---
title: "Final Project Quarto"
author: "Jessica Varnell"
format: html
editor: visual
theme: sketchy
execute: 
  cache: true
---

This data set includes information on all participants (survivalists) that have been a part of the Netflix series "Alone".

## Descriptive Statistics

```{r}
#| include: false
library(gtsummary)
library(tidyverse)
library(alone)
library(tidytuesdayR)
tuesdata <- tidytuesdayR::tt_load(2023, week = 4)
alone <- tuesdata$survivalists
```

```{r}
#| echo: false
#| label: tbl-one
#| tbl-cap: "Descriptive Statistics"
#| warning: false
table1 <- tbl_summary(alone, by = gender,
include = c(age, gender, country, days_lasted, reason_category, medically_evacuated),
label = list(
  age ~ "Age",
  gender ~ "Gender",
  country ~ "Country of Residence",
  days_lasted ~ "# of Days Lasted",
  reason_category ~ "Reason for Tapping Out - Category",
  medically_evacuated ~ "Medically Evacuated?"
),
missing_text = "N/A - Winner") %>% 
  add_p(test=list(all_continuous() ~ "t.test",
                  all_categorical() ~ "chisq.test")) %>% 
  bold_labels() %>% 
  modify_header(label="**Variable**", p.value = "**p**")

table1
```

## Regression Table

```{r}
#| echo: false
#| label: tbl-two
#| tbl-cap: "Linear Regression"
table2 <- tbl_uvregression(alone, x=gender, include = 
                   c(age, days_lasted, result), label= list(
                   age ~ "Age",
                   days_lasted ~ "Days Lasted",
                   result ~ "Place Finished"
                   ), method=lm)
table2
```
